# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='health_department',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
