# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-01 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20191101_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='hood_name',
            new_name='location',
        ),
    ]
