# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-03 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
